name: CI/CD Pipeline for React App

on:
  push:
    branches: [main]
  # workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: print Helloo
        run: echo "Hello world"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.164.192.230
          username: ubuntu
          key: ${{ secrets.EC2_PASSWORD }}
          port: 22
          script: |
            ls
            cd EC2
            git pull origin main 
            npm install
            pm2 restart nextapp
            
         
            

        