# name: ci/cd for react app

# on:
#   push:
#     branches: [ main ]
#   workflow_dispatch:

# permissions:
#   contents: write 

# jobs:
  
#   build-and-deploy:
    
#     runs-on: ubuntu-latest
      
#        steps:
#         - name: checkout Repository
#           uses: actions/checkout@v3

#         - name: Setup Node.js
#           uses: actions/setup-node@v3
#             with:
#               node-version: 18

#         - name: Install Dependencies 
#             run: npm install

#         - name: Build Project  
#             run: npm run build 
        
#         - name: Deploy To GitHub Pages 
#           uses: JamesIves/github-pages-deploy-action@4.1.0
#           with:
#             branch: gh-pages
#             folder: build 


# name: CI/CD Pipline for React App

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# permissions:
#   contents: write

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: npm install

#       - name: Build Project
#         run: npm run build
#         env:
#           REACT_APP_WELCOME_TEXT: ${{ vars.REACT_APP_WELCOME_TEXT }}

#       - name: Deploy to GitHub Pages
#         uses: JamesIves/github-pages-deploy-action@4.1.0
#         with:
#           branch: gh-pages
#           folder: build

    
# name: CI/CD Pipeline for React App

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# permissions:
#   contents: write

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 14

#       - name: Install dependencies
#         run: npm install

#       - name: Build Project
#         run: npm run build
#         env:
#           REACT_APP_WELCOME_TEXT: ${{ secrets.REACT_APP_WELCOME_TEXT }}

#       - name: Deploy to EC2
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           password: ${{ secrets.EC2_PASSWORD }}
#           source: "build/*"
#           target: "/path/to/your/app/on/ec2/"

# name: CI/CD Pipeline for React App

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# permissions:
#   contents: write

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 14

#       - name: Install dependencies
#         run: npm install

#       - name: Build Project
#         run: npm run build
#         env:
#           REACT_APP_WELCOME_TEXT: ${{ secrets.REACT_APP_WELCOME_TEXT }}

#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_PASSWORD}}
#           port: ${{ secrets.EC2_PORT }}
#           script: |
#             ls
#             cd EC2
#             git pull origin main
#             ls
#             npm i 
#             pm2 restart nextapp


name: CI/CD Pipeline for React App

on:
  push:
    branches: [main]
  # workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 14

      # - name: Install dependencies
      #   run: npm install

      # - name: Build Project
      #   run: npm run build
      #   env:
      #     REACT_APP_WELCOME_TEXT: ${{ secrets.REACT_APP_WELCOME_TEXT }}

      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@4.1.0
      #   with:
      #     branch: gh-pages
      #     folder: build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd EC2
            ls
            # git pull origin main
            # npm install  
            # pm2 restart nextapp

